-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity adc_to_opfb is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    istream_data_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    istream_data_TVALID : IN STD_LOGIC;
    istream_data_TREADY : OUT STD_LOGIC;
    qstream_data_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    qstream_data_TVALID : IN STD_LOGIC;
    qstream_data_TREADY : OUT STD_LOGIC;
    lane_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_0_TVALID : OUT STD_LOGIC;
    lane_0_TREADY : IN STD_LOGIC;
    lane_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_1_TVALID : OUT STD_LOGIC;
    lane_1_TREADY : IN STD_LOGIC;
    lane_2_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_2_TVALID : OUT STD_LOGIC;
    lane_2_TREADY : IN STD_LOGIC;
    lane_3_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_3_TVALID : OUT STD_LOGIC;
    lane_3_TREADY : IN STD_LOGIC;
    lane_4_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_4_TVALID : OUT STD_LOGIC;
    lane_4_TREADY : IN STD_LOGIC;
    lane_5_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_5_TVALID : OUT STD_LOGIC;
    lane_5_TREADY : IN STD_LOGIC;
    lane_6_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_6_TVALID : OUT STD_LOGIC;
    lane_6_TREADY : IN STD_LOGIC;
    lane_7_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_7_TVALID : OUT STD_LOGIC;
    lane_7_TREADY : IN STD_LOGIC;
    lane_8_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_8_TVALID : OUT STD_LOGIC;
    lane_8_TREADY : IN STD_LOGIC;
    lane_9_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_9_TVALID : OUT STD_LOGIC;
    lane_9_TREADY : IN STD_LOGIC;
    lane_10_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_10_TVALID : OUT STD_LOGIC;
    lane_10_TREADY : IN STD_LOGIC;
    lane_11_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_11_TVALID : OUT STD_LOGIC;
    lane_11_TREADY : IN STD_LOGIC;
    lane_12_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_12_TVALID : OUT STD_LOGIC;
    lane_12_TREADY : IN STD_LOGIC;
    lane_13_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_13_TVALID : OUT STD_LOGIC;
    lane_13_TREADY : IN STD_LOGIC;
    lane_14_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_14_TVALID : OUT STD_LOGIC;
    lane_14_TREADY : IN STD_LOGIC;
    lane_15_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    lane_15_TVALID : OUT STD_LOGIC;
    lane_15_TREADY : IN STD_LOGIC;
    lane_0_TLAST : OUT STD_LOGIC;
    lane_1_TLAST : OUT STD_LOGIC;
    lane_2_TLAST : OUT STD_LOGIC;
    lane_3_TLAST : OUT STD_LOGIC;
    lane_4_TLAST : OUT STD_LOGIC;
    lane_5_TLAST : OUT STD_LOGIC;
    lane_6_TLAST : OUT STD_LOGIC;
    lane_7_TLAST : OUT STD_LOGIC;
    lane_8_TLAST : OUT STD_LOGIC;
    lane_9_TLAST : OUT STD_LOGIC;
    lane_10_TLAST : OUT STD_LOGIC;
    lane_11_TLAST : OUT STD_LOGIC;
    lane_12_TLAST : OUT STD_LOGIC;
    lane_13_TLAST : OUT STD_LOGIC;
    lane_14_TLAST : OUT STD_LOGIC;
    lane_15_TLAST : OUT STD_LOGIC );
end;


architecture behav of adc_to_opfb is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "adc_to_opfb,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=1.953000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.849000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=778,HLS_SYN_LUT=712,HLS_VERSION=2019_2_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal cycle_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal last_V_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal even_lane_z1_V_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal last_V_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal istream_data_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal qstream_data_TDATA_blk_n : STD_LOGIC;
    signal lane_0_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal lane_1_TDATA_blk_n : STD_LOGIC;
    signal lane_2_TDATA_blk_n : STD_LOGIC;
    signal lane_3_TDATA_blk_n : STD_LOGIC;
    signal lane_4_TDATA_blk_n : STD_LOGIC;
    signal lane_5_TDATA_blk_n : STD_LOGIC;
    signal lane_6_TDATA_blk_n : STD_LOGIC;
    signal lane_7_TDATA_blk_n : STD_LOGIC;
    signal lane_8_TDATA_blk_n : STD_LOGIC;
    signal lane_9_TDATA_blk_n : STD_LOGIC;
    signal lane_10_TDATA_blk_n : STD_LOGIC;
    signal lane_11_TDATA_blk_n : STD_LOGIC;
    signal lane_12_TDATA_blk_n : STD_LOGIC;
    signal lane_13_TDATA_blk_n : STD_LOGIC;
    signal lane_14_TDATA_blk_n : STD_LOGIC;
    signal lane_15_TDATA_blk_n : STD_LOGIC;
    signal trunc_ln791_fu_570_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal regslice_forward_lane_0_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_1_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_2_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_3_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_4_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_5_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_6_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_7_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_8_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_9_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_10_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_11_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_12_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_13_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_14_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_forward_lane_15_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln879_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal add_ln700_fu_980_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal iq_0_V_write_assign_fu_502_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_fu_578_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_1_V_write_assign_fu_510_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_2_fu_648_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_2_V_write_assign_fu_518_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_4_fu_696_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_3_V_write_assign_fu_526_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_6_fu_744_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_4_V_write_assign_fu_534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_8_fu_792_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_5_V_write_assign_fu_542_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_10_fu_840_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_6_V_write_assign_fu_550_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_12_fu_888_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iq_7_V_write_assign_fu_558_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_14_fu_936_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln77_1_fu_428_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln77_fu_354_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_8_fu_432_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_1_fu_358_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_9_fu_442_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_2_fu_368_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_s_fu_452_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_3_fu_378_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_10_fu_462_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_4_fu_388_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_11_fu_472_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_5_fu_398_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_12_fu_482_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_6_fu_408_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_13_fu_492_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_7_fu_418_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_reverse_istream_data_U_apdone_blk : STD_LOGIC;
    signal istream_data_TDATA_int : STD_LOGIC_VECTOR (127 downto 0);
    signal istream_data_TVALID_int : STD_LOGIC;
    signal istream_data_TREADY_int : STD_LOGIC;
    signal regslice_reverse_istream_data_U_ack_in : STD_LOGIC;
    signal regslice_reverse_qstream_data_U_apdone_blk : STD_LOGIC;
    signal qstream_data_TDATA_int : STD_LOGIC_VECTOR (127 downto 0);
    signal qstream_data_TVALID_int : STD_LOGIC;
    signal qstream_data_TREADY_int : STD_LOGIC;
    signal regslice_reverse_qstream_data_U_ack_in : STD_LOGIC;
    signal lane_0_TVALID_int : STD_LOGIC;
    signal lane_0_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_0_data_V_U_vld_out : STD_LOGIC;
    signal lane_1_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_1_TVALID_int : STD_LOGIC;
    signal lane_1_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_1_data_V_U_vld_out : STD_LOGIC;
    signal lane_2_TVALID_int : STD_LOGIC;
    signal lane_2_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_2_data_V_U_vld_out : STD_LOGIC;
    signal lane_3_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_3_TVALID_int : STD_LOGIC;
    signal lane_3_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_3_data_V_U_vld_out : STD_LOGIC;
    signal lane_4_TVALID_int : STD_LOGIC;
    signal lane_4_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_4_data_V_U_vld_out : STD_LOGIC;
    signal lane_5_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_5_TVALID_int : STD_LOGIC;
    signal lane_5_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_5_data_V_U_vld_out : STD_LOGIC;
    signal lane_6_TVALID_int : STD_LOGIC;
    signal lane_6_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_6_data_V_U_vld_out : STD_LOGIC;
    signal lane_7_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_7_TVALID_int : STD_LOGIC;
    signal lane_7_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_7_data_V_U_vld_out : STD_LOGIC;
    signal lane_8_TVALID_int : STD_LOGIC;
    signal lane_8_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_8_data_V_U_vld_out : STD_LOGIC;
    signal lane_9_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_9_TVALID_int : STD_LOGIC;
    signal lane_9_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_9_data_V_U_vld_out : STD_LOGIC;
    signal lane_10_TVALID_int : STD_LOGIC;
    signal lane_10_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_10_data_V_U_vld_out : STD_LOGIC;
    signal lane_11_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_11_TVALID_int : STD_LOGIC;
    signal lane_11_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_11_data_V_U_vld_out : STD_LOGIC;
    signal lane_12_TVALID_int : STD_LOGIC;
    signal lane_12_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_12_data_V_U_vld_out : STD_LOGIC;
    signal lane_13_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_13_TVALID_int : STD_LOGIC;
    signal lane_13_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_13_data_V_U_vld_out : STD_LOGIC;
    signal lane_14_TVALID_int : STD_LOGIC;
    signal lane_14_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_14_data_V_U_vld_out : STD_LOGIC;
    signal lane_15_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal lane_15_TVALID_int : STD_LOGIC;
    signal lane_15_TREADY_int : STD_LOGIC;
    signal regslice_forward_lane_15_data_V_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_0_last_U_apdone_blk : STD_LOGIC;
    signal lane_0_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_0_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_0_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_1_last_U_apdone_blk : STD_LOGIC;
    signal lane_1_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_1_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_1_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_2_last_U_apdone_blk : STD_LOGIC;
    signal lane_2_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_2_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_2_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_3_last_U_apdone_blk : STD_LOGIC;
    signal lane_3_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_3_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_3_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_4_last_U_apdone_blk : STD_LOGIC;
    signal lane_4_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_4_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_4_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_5_last_U_apdone_blk : STD_LOGIC;
    signal lane_5_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_5_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_5_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_6_last_U_apdone_blk : STD_LOGIC;
    signal lane_6_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_6_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_6_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_7_last_U_apdone_blk : STD_LOGIC;
    signal lane_7_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_7_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_7_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_8_last_U_apdone_blk : STD_LOGIC;
    signal lane_8_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_8_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_8_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_9_last_U_apdone_blk : STD_LOGIC;
    signal lane_9_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_9_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_9_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_10_last_U_apdone_blk : STD_LOGIC;
    signal lane_10_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_10_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_10_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_11_last_U_apdone_blk : STD_LOGIC;
    signal lane_11_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_11_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_11_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_12_last_U_apdone_blk : STD_LOGIC;
    signal lane_12_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_12_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_12_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_13_last_U_apdone_blk : STD_LOGIC;
    signal lane_13_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_13_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_13_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_14_last_U_apdone_blk : STD_LOGIC;
    signal lane_14_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_14_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_14_last_U_vld_out : STD_LOGIC;
    signal regslice_forward_w1_lane_15_last_U_apdone_blk : STD_LOGIC;
    signal lane_15_TLAST_int : STD_LOGIC;
    signal regslice_forward_w1_lane_15_last_U_ack_in_dummy : STD_LOGIC;
    signal regslice_forward_w1_lane_15_last_U_vld_out : STD_LOGIC;

    component regslice_reverse IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;


    component regslice_forward IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;


    component regslice_forward_w1 IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC;
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC;
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_reverse_istream_data_U : component regslice_reverse
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => istream_data_TDATA,
        vld_in => istream_data_TVALID,
        ack_in => regslice_reverse_istream_data_U_ack_in,
        data_out => istream_data_TDATA_int,
        vld_out => istream_data_TVALID_int,
        ack_out => istream_data_TREADY_int,
        apdone_blk => regslice_reverse_istream_data_U_apdone_blk);

    regslice_reverse_qstream_data_U : component regslice_reverse
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => qstream_data_TDATA,
        vld_in => qstream_data_TVALID,
        ack_in => regslice_reverse_qstream_data_U_ack_in,
        data_out => qstream_data_TDATA_int,
        vld_out => qstream_data_TVALID_int,
        ack_out => qstream_data_TREADY_int,
        apdone_blk => regslice_reverse_qstream_data_U_apdone_blk);

    regslice_forward_lane_0_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_0,
        vld_in => lane_0_TVALID_int,
        ack_in => lane_0_TREADY_int,
        data_out => lane_0_TDATA,
        vld_out => regslice_forward_lane_0_data_V_U_vld_out,
        ack_out => lane_0_TREADY,
        apdone_blk => regslice_forward_lane_0_data_V_U_apdone_blk);

    regslice_forward_lane_1_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_1_TDATA_int,
        vld_in => lane_1_TVALID_int,
        ack_in => lane_1_TREADY_int,
        data_out => lane_1_TDATA,
        vld_out => regslice_forward_lane_1_data_V_U_vld_out,
        ack_out => lane_1_TREADY,
        apdone_blk => regslice_forward_lane_1_data_V_U_apdone_blk);

    regslice_forward_lane_2_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_1,
        vld_in => lane_2_TVALID_int,
        ack_in => lane_2_TREADY_int,
        data_out => lane_2_TDATA,
        vld_out => regslice_forward_lane_2_data_V_U_vld_out,
        ack_out => lane_2_TREADY,
        apdone_blk => regslice_forward_lane_2_data_V_U_apdone_blk);

    regslice_forward_lane_3_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_3_TDATA_int,
        vld_in => lane_3_TVALID_int,
        ack_in => lane_3_TREADY_int,
        data_out => lane_3_TDATA,
        vld_out => regslice_forward_lane_3_data_V_U_vld_out,
        ack_out => lane_3_TREADY,
        apdone_blk => regslice_forward_lane_3_data_V_U_apdone_blk);

    regslice_forward_lane_4_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_2,
        vld_in => lane_4_TVALID_int,
        ack_in => lane_4_TREADY_int,
        data_out => lane_4_TDATA,
        vld_out => regslice_forward_lane_4_data_V_U_vld_out,
        ack_out => lane_4_TREADY,
        apdone_blk => regslice_forward_lane_4_data_V_U_apdone_blk);

    regslice_forward_lane_5_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_5_TDATA_int,
        vld_in => lane_5_TVALID_int,
        ack_in => lane_5_TREADY_int,
        data_out => lane_5_TDATA,
        vld_out => regslice_forward_lane_5_data_V_U_vld_out,
        ack_out => lane_5_TREADY,
        apdone_blk => regslice_forward_lane_5_data_V_U_apdone_blk);

    regslice_forward_lane_6_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_3,
        vld_in => lane_6_TVALID_int,
        ack_in => lane_6_TREADY_int,
        data_out => lane_6_TDATA,
        vld_out => regslice_forward_lane_6_data_V_U_vld_out,
        ack_out => lane_6_TREADY,
        apdone_blk => regslice_forward_lane_6_data_V_U_apdone_blk);

    regslice_forward_lane_7_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_7_TDATA_int,
        vld_in => lane_7_TVALID_int,
        ack_in => lane_7_TREADY_int,
        data_out => lane_7_TDATA,
        vld_out => regslice_forward_lane_7_data_V_U_vld_out,
        ack_out => lane_7_TREADY,
        apdone_blk => regslice_forward_lane_7_data_V_U_apdone_blk);

    regslice_forward_lane_8_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_4,
        vld_in => lane_8_TVALID_int,
        ack_in => lane_8_TREADY_int,
        data_out => lane_8_TDATA,
        vld_out => regslice_forward_lane_8_data_V_U_vld_out,
        ack_out => lane_8_TREADY,
        apdone_blk => regslice_forward_lane_8_data_V_U_apdone_blk);

    regslice_forward_lane_9_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_9_TDATA_int,
        vld_in => lane_9_TVALID_int,
        ack_in => lane_9_TREADY_int,
        data_out => lane_9_TDATA,
        vld_out => regslice_forward_lane_9_data_V_U_vld_out,
        ack_out => lane_9_TREADY,
        apdone_blk => regslice_forward_lane_9_data_V_U_apdone_blk);

    regslice_forward_lane_10_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_5,
        vld_in => lane_10_TVALID_int,
        ack_in => lane_10_TREADY_int,
        data_out => lane_10_TDATA,
        vld_out => regslice_forward_lane_10_data_V_U_vld_out,
        ack_out => lane_10_TREADY,
        apdone_blk => regslice_forward_lane_10_data_V_U_apdone_blk);

    regslice_forward_lane_11_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_11_TDATA_int,
        vld_in => lane_11_TVALID_int,
        ack_in => lane_11_TREADY_int,
        data_out => lane_11_TDATA,
        vld_out => regslice_forward_lane_11_data_V_U_vld_out,
        ack_out => lane_11_TREADY,
        apdone_blk => regslice_forward_lane_11_data_V_U_apdone_blk);

    regslice_forward_lane_12_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_6,
        vld_in => lane_12_TVALID_int,
        ack_in => lane_12_TREADY_int,
        data_out => lane_12_TDATA,
        vld_out => regslice_forward_lane_12_data_V_U_vld_out,
        ack_out => lane_12_TREADY,
        apdone_blk => regslice_forward_lane_12_data_V_U_apdone_blk);

    regslice_forward_lane_13_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_13_TDATA_int,
        vld_in => lane_13_TVALID_int,
        ack_in => lane_13_TREADY_int,
        data_out => lane_13_TDATA,
        vld_out => regslice_forward_lane_13_data_V_U_vld_out,
        ack_out => lane_13_TREADY,
        apdone_blk => regslice_forward_lane_13_data_V_U_apdone_blk);

    regslice_forward_lane_14_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => even_lane_z1_V_7,
        vld_in => lane_14_TVALID_int,
        ack_in => lane_14_TREADY_int,
        data_out => lane_14_TDATA,
        vld_out => regslice_forward_lane_14_data_V_U_vld_out,
        ack_out => lane_14_TREADY,
        apdone_blk => regslice_forward_lane_14_data_V_U_apdone_blk);

    regslice_forward_lane_15_data_V_U : component regslice_forward
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_15_TDATA_int,
        vld_in => lane_15_TVALID_int,
        ack_in => lane_15_TREADY_int,
        data_out => lane_15_TDATA,
        vld_out => regslice_forward_lane_15_data_V_U_vld_out,
        ack_out => lane_15_TREADY,
        apdone_blk => regslice_forward_lane_15_data_V_U_apdone_blk);

    regslice_forward_w1_lane_0_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_0_TLAST_int,
        vld_in => lane_0_TVALID_int,
        ack_in => regslice_forward_w1_lane_0_last_U_ack_in_dummy,
        data_out => lane_0_TLAST,
        vld_out => regslice_forward_w1_lane_0_last_U_vld_out,
        ack_out => lane_0_TREADY,
        apdone_blk => regslice_forward_w1_lane_0_last_U_apdone_blk);

    regslice_forward_w1_lane_1_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_1_TLAST_int,
        vld_in => lane_1_TVALID_int,
        ack_in => regslice_forward_w1_lane_1_last_U_ack_in_dummy,
        data_out => lane_1_TLAST,
        vld_out => regslice_forward_w1_lane_1_last_U_vld_out,
        ack_out => lane_1_TREADY,
        apdone_blk => regslice_forward_w1_lane_1_last_U_apdone_blk);

    regslice_forward_w1_lane_2_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_2_TLAST_int,
        vld_in => lane_2_TVALID_int,
        ack_in => regslice_forward_w1_lane_2_last_U_ack_in_dummy,
        data_out => lane_2_TLAST,
        vld_out => regslice_forward_w1_lane_2_last_U_vld_out,
        ack_out => lane_2_TREADY,
        apdone_blk => regslice_forward_w1_lane_2_last_U_apdone_blk);

    regslice_forward_w1_lane_3_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_3_TLAST_int,
        vld_in => lane_3_TVALID_int,
        ack_in => regslice_forward_w1_lane_3_last_U_ack_in_dummy,
        data_out => lane_3_TLAST,
        vld_out => regslice_forward_w1_lane_3_last_U_vld_out,
        ack_out => lane_3_TREADY,
        apdone_blk => regslice_forward_w1_lane_3_last_U_apdone_blk);

    regslice_forward_w1_lane_4_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_4_TLAST_int,
        vld_in => lane_4_TVALID_int,
        ack_in => regslice_forward_w1_lane_4_last_U_ack_in_dummy,
        data_out => lane_4_TLAST,
        vld_out => regslice_forward_w1_lane_4_last_U_vld_out,
        ack_out => lane_4_TREADY,
        apdone_blk => regslice_forward_w1_lane_4_last_U_apdone_blk);

    regslice_forward_w1_lane_5_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_5_TLAST_int,
        vld_in => lane_5_TVALID_int,
        ack_in => regslice_forward_w1_lane_5_last_U_ack_in_dummy,
        data_out => lane_5_TLAST,
        vld_out => regslice_forward_w1_lane_5_last_U_vld_out,
        ack_out => lane_5_TREADY,
        apdone_blk => regslice_forward_w1_lane_5_last_U_apdone_blk);

    regslice_forward_w1_lane_6_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_6_TLAST_int,
        vld_in => lane_6_TVALID_int,
        ack_in => regslice_forward_w1_lane_6_last_U_ack_in_dummy,
        data_out => lane_6_TLAST,
        vld_out => regslice_forward_w1_lane_6_last_U_vld_out,
        ack_out => lane_6_TREADY,
        apdone_blk => regslice_forward_w1_lane_6_last_U_apdone_blk);

    regslice_forward_w1_lane_7_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_7_TLAST_int,
        vld_in => lane_7_TVALID_int,
        ack_in => regslice_forward_w1_lane_7_last_U_ack_in_dummy,
        data_out => lane_7_TLAST,
        vld_out => regslice_forward_w1_lane_7_last_U_vld_out,
        ack_out => lane_7_TREADY,
        apdone_blk => regslice_forward_w1_lane_7_last_U_apdone_blk);

    regslice_forward_w1_lane_8_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_8_TLAST_int,
        vld_in => lane_8_TVALID_int,
        ack_in => regslice_forward_w1_lane_8_last_U_ack_in_dummy,
        data_out => lane_8_TLAST,
        vld_out => regslice_forward_w1_lane_8_last_U_vld_out,
        ack_out => lane_8_TREADY,
        apdone_blk => regslice_forward_w1_lane_8_last_U_apdone_blk);

    regslice_forward_w1_lane_9_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_9_TLAST_int,
        vld_in => lane_9_TVALID_int,
        ack_in => regslice_forward_w1_lane_9_last_U_ack_in_dummy,
        data_out => lane_9_TLAST,
        vld_out => regslice_forward_w1_lane_9_last_U_vld_out,
        ack_out => lane_9_TREADY,
        apdone_blk => regslice_forward_w1_lane_9_last_U_apdone_blk);

    regslice_forward_w1_lane_10_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_10_TLAST_int,
        vld_in => lane_10_TVALID_int,
        ack_in => regslice_forward_w1_lane_10_last_U_ack_in_dummy,
        data_out => lane_10_TLAST,
        vld_out => regslice_forward_w1_lane_10_last_U_vld_out,
        ack_out => lane_10_TREADY,
        apdone_blk => regslice_forward_w1_lane_10_last_U_apdone_blk);

    regslice_forward_w1_lane_11_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_11_TLAST_int,
        vld_in => lane_11_TVALID_int,
        ack_in => regslice_forward_w1_lane_11_last_U_ack_in_dummy,
        data_out => lane_11_TLAST,
        vld_out => regslice_forward_w1_lane_11_last_U_vld_out,
        ack_out => lane_11_TREADY,
        apdone_blk => regslice_forward_w1_lane_11_last_U_apdone_blk);

    regslice_forward_w1_lane_12_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_12_TLAST_int,
        vld_in => lane_12_TVALID_int,
        ack_in => regslice_forward_w1_lane_12_last_U_ack_in_dummy,
        data_out => lane_12_TLAST,
        vld_out => regslice_forward_w1_lane_12_last_U_vld_out,
        ack_out => lane_12_TREADY,
        apdone_blk => regslice_forward_w1_lane_12_last_U_apdone_blk);

    regslice_forward_w1_lane_13_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_13_TLAST_int,
        vld_in => lane_13_TVALID_int,
        ack_in => regslice_forward_w1_lane_13_last_U_ack_in_dummy,
        data_out => lane_13_TLAST,
        vld_out => regslice_forward_w1_lane_13_last_U_vld_out,
        ack_out => lane_13_TREADY,
        apdone_blk => regslice_forward_w1_lane_13_last_U_apdone_blk);

    regslice_forward_w1_lane_14_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_14_TLAST_int,
        vld_in => lane_14_TVALID_int,
        ack_in => regslice_forward_w1_lane_14_last_U_ack_in_dummy,
        data_out => lane_14_TLAST,
        vld_out => regslice_forward_w1_lane_14_last_U_vld_out,
        ack_out => lane_14_TREADY,
        apdone_blk => regslice_forward_w1_lane_14_last_U_apdone_blk);

    regslice_forward_w1_lane_15_last_U : component regslice_forward_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => lane_15_TLAST_int,
        vld_in => lane_15_TVALID_int,
        ack_in => regslice_forward_w1_lane_15_last_U_ack_in_dummy,
        data_out => lane_15_TLAST,
        vld_out => regslice_forward_w1_lane_15_last_U_vld_out,
        ack_out => lane_15_TREADY,
        apdone_blk => regslice_forward_w1_lane_15_last_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cycle_V <= add_ln700_fu_980_p2;
                even_lane_z1_V_0 <= select_ln43_fu_578_p3;
                even_lane_z1_V_1 <= select_ln43_2_fu_648_p3;
                even_lane_z1_V_2 <= select_ln43_4_fu_696_p3;
                even_lane_z1_V_3 <= select_ln43_6_fu_744_p3;
                even_lane_z1_V_4 <= select_ln43_8_fu_792_p3;
                even_lane_z1_V_5 <= select_ln43_10_fu_840_p3;
                even_lane_z1_V_6 <= select_ln43_12_fu_888_p3;
                even_lane_z1_V_7 <= select_ln43_14_fu_936_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln791_fu_570_p1 = ap_const_lv1_0))) then
                last_V_0 <= iq_0_V_write_assign_fu_502_p3;
                last_V_10 <= iq_5_V_write_assign_fu_542_p3;
                last_V_12 <= iq_6_V_write_assign_fu_550_p3;
                last_V_14 <= iq_7_V_write_assign_fu_558_p3;
                last_V_2 <= iq_1_V_write_assign_fu_510_p3;
                last_V_4 <= iq_2_V_write_assign_fu_518_p3;
                last_V_6 <= iq_3_V_write_assign_fu_526_p3;
                last_V_8 <= iq_4_V_write_assign_fu_534_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln791_fu_570_p1 = ap_const_lv1_1))) then
                last_V_1 <= iq_0_V_write_assign_fu_502_p3;
                last_V_11 <= iq_5_V_write_assign_fu_542_p3;
                last_V_13 <= iq_6_V_write_assign_fu_550_p3;
                last_V_15 <= iq_7_V_write_assign_fu_558_p3;
                last_V_3 <= iq_1_V_write_assign_fu_510_p3;
                last_V_5 <= iq_2_V_write_assign_fu_518_p3;
                last_V_7 <= iq_3_V_write_assign_fu_526_p3;
                last_V_9 <= iq_4_V_write_assign_fu_534_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln700_fu_980_p2 <= std_logic_vector(unsigned(cycle_V) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, regslice_forward_lane_0_data_V_U_apdone_blk, regslice_forward_lane_1_data_V_U_apdone_blk, regslice_forward_lane_2_data_V_U_apdone_blk, regslice_forward_lane_3_data_V_U_apdone_blk, regslice_forward_lane_4_data_V_U_apdone_blk, regslice_forward_lane_5_data_V_U_apdone_blk, regslice_forward_lane_6_data_V_U_apdone_blk, regslice_forward_lane_7_data_V_U_apdone_blk, regslice_forward_lane_8_data_V_U_apdone_blk, regslice_forward_lane_9_data_V_U_apdone_blk, regslice_forward_lane_10_data_V_U_apdone_blk, regslice_forward_lane_11_data_V_U_apdone_blk, regslice_forward_lane_12_data_V_U_apdone_blk, regslice_forward_lane_13_data_V_U_apdone_blk, regslice_forward_lane_14_data_V_U_apdone_blk, regslice_forward_lane_15_data_V_U_apdone_blk, istream_data_TVALID_int, qstream_data_TVALID_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_forward_lane_15_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_14_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_13_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_12_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_11_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_10_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_9_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_8_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_7_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_6_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_5_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_4_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_3_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_2_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_1_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_0_data_V_U_apdone_blk = ap_const_logic_1))) or ((ap_const_logic_1 = ap_const_logic_1) and ((qstream_data_TVALID_int = ap_const_logic_0) or (istream_data_TVALID_int = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_io, regslice_forward_lane_0_data_V_U_apdone_blk, regslice_forward_lane_1_data_V_U_apdone_blk, regslice_forward_lane_2_data_V_U_apdone_blk, regslice_forward_lane_3_data_V_U_apdone_blk, regslice_forward_lane_4_data_V_U_apdone_blk, regslice_forward_lane_5_data_V_U_apdone_blk, regslice_forward_lane_6_data_V_U_apdone_blk, regslice_forward_lane_7_data_V_U_apdone_blk, regslice_forward_lane_8_data_V_U_apdone_blk, regslice_forward_lane_9_data_V_U_apdone_blk, regslice_forward_lane_10_data_V_U_apdone_blk, regslice_forward_lane_11_data_V_U_apdone_blk, regslice_forward_lane_12_data_V_U_apdone_blk, regslice_forward_lane_13_data_V_U_apdone_blk, regslice_forward_lane_14_data_V_U_apdone_blk, regslice_forward_lane_15_data_V_U_apdone_blk, ap_block_state2_io, istream_data_TVALID_int, qstream_data_TVALID_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_forward_lane_15_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_14_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_13_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_12_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_11_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_10_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_9_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_8_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_7_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_6_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_5_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_4_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_3_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_2_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_1_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_0_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) or ((ap_const_logic_1 = ap_const_logic_1) and ((qstream_data_TVALID_int = ap_const_logic_0) or (istream_data_TVALID_int = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_io, regslice_forward_lane_0_data_V_U_apdone_blk, regslice_forward_lane_1_data_V_U_apdone_blk, regslice_forward_lane_2_data_V_U_apdone_blk, regslice_forward_lane_3_data_V_U_apdone_blk, regslice_forward_lane_4_data_V_U_apdone_blk, regslice_forward_lane_5_data_V_U_apdone_blk, regslice_forward_lane_6_data_V_U_apdone_blk, regslice_forward_lane_7_data_V_U_apdone_blk, regslice_forward_lane_8_data_V_U_apdone_blk, regslice_forward_lane_9_data_V_U_apdone_blk, regslice_forward_lane_10_data_V_U_apdone_blk, regslice_forward_lane_11_data_V_U_apdone_blk, regslice_forward_lane_12_data_V_U_apdone_blk, regslice_forward_lane_13_data_V_U_apdone_blk, regslice_forward_lane_14_data_V_U_apdone_blk, regslice_forward_lane_15_data_V_U_apdone_blk, ap_block_state2_io, istream_data_TVALID_int, qstream_data_TVALID_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_forward_lane_15_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_14_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_13_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_12_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_11_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_10_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_9_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_8_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_7_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_6_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_5_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_4_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_3_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_2_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_1_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_0_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) or ((ap_const_logic_1 = ap_const_logic_1) and ((qstream_data_TVALID_int = ap_const_logic_0) or (istream_data_TVALID_int = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))));
    end process;


    ap_block_state1_io_assign_proc : process(lane_0_TREADY_int, lane_1_TREADY_int, lane_2_TREADY_int, lane_3_TREADY_int, lane_4_TREADY_int, lane_5_TREADY_int, lane_6_TREADY_int, lane_7_TREADY_int, lane_8_TREADY_int, lane_9_TREADY_int, lane_10_TREADY_int, lane_11_TREADY_int, lane_12_TREADY_int, lane_13_TREADY_int, lane_14_TREADY_int, lane_15_TREADY_int)
    begin
                ap_block_state1_io <= ((lane_15_TREADY_int = ap_const_logic_0) or (lane_14_TREADY_int = ap_const_logic_0) or (lane_13_TREADY_int = ap_const_logic_0) or (lane_12_TREADY_int = ap_const_logic_0) or (lane_11_TREADY_int = ap_const_logic_0) or (lane_10_TREADY_int = ap_const_logic_0) or (lane_9_TREADY_int = ap_const_logic_0) or (lane_8_TREADY_int = ap_const_logic_0) or (lane_7_TREADY_int = ap_const_logic_0) or (lane_6_TREADY_int = ap_const_logic_0) or (lane_5_TREADY_int = ap_const_logic_0) or (lane_4_TREADY_int = ap_const_logic_0) or (lane_3_TREADY_int = ap_const_logic_0) or (lane_2_TREADY_int = ap_const_logic_0) or (lane_1_TREADY_int = ap_const_logic_0) or (lane_0_TREADY_int = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(istream_data_TVALID_int, qstream_data_TVALID_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((qstream_data_TVALID_int = ap_const_logic_0) or (istream_data_TVALID_int = ap_const_logic_0));
    end process;


    ap_block_state2_io_assign_proc : process(lane_0_TREADY_int, lane_1_TREADY_int, lane_2_TREADY_int, lane_3_TREADY_int, lane_4_TREADY_int, lane_5_TREADY_int, lane_6_TREADY_int, lane_7_TREADY_int, lane_8_TREADY_int, lane_9_TREADY_int, lane_10_TREADY_int, lane_11_TREADY_int, lane_12_TREADY_int, lane_13_TREADY_int, lane_14_TREADY_int, lane_15_TREADY_int)
    begin
                ap_block_state2_io <= ((lane_15_TREADY_int = ap_const_logic_0) or (lane_14_TREADY_int = ap_const_logic_0) or (lane_13_TREADY_int = ap_const_logic_0) or (lane_12_TREADY_int = ap_const_logic_0) or (lane_11_TREADY_int = ap_const_logic_0) or (lane_10_TREADY_int = ap_const_logic_0) or (lane_9_TREADY_int = ap_const_logic_0) or (lane_8_TREADY_int = ap_const_logic_0) or (lane_7_TREADY_int = ap_const_logic_0) or (lane_6_TREADY_int = ap_const_logic_0) or (lane_5_TREADY_int = ap_const_logic_0) or (lane_4_TREADY_int = ap_const_logic_0) or (lane_3_TREADY_int = ap_const_logic_0) or (lane_2_TREADY_int = ap_const_logic_0) or (lane_1_TREADY_int = ap_const_logic_0) or (lane_0_TREADY_int = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_forward_lane_0_data_V_U_apdone_blk, regslice_forward_lane_1_data_V_U_apdone_blk, regslice_forward_lane_2_data_V_U_apdone_blk, regslice_forward_lane_3_data_V_U_apdone_blk, regslice_forward_lane_4_data_V_U_apdone_blk, regslice_forward_lane_5_data_V_U_apdone_blk, regslice_forward_lane_6_data_V_U_apdone_blk, regslice_forward_lane_7_data_V_U_apdone_blk, regslice_forward_lane_8_data_V_U_apdone_blk, regslice_forward_lane_9_data_V_U_apdone_blk, regslice_forward_lane_10_data_V_U_apdone_blk, regslice_forward_lane_11_data_V_U_apdone_blk, regslice_forward_lane_12_data_V_U_apdone_blk, regslice_forward_lane_13_data_V_U_apdone_blk, regslice_forward_lane_14_data_V_U_apdone_blk, regslice_forward_lane_15_data_V_U_apdone_blk)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_forward_lane_15_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_14_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_13_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_12_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_11_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_10_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_9_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_8_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_7_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_6_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_5_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_4_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_3_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_2_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_1_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_forward_lane_0_data_V_U_apdone_blk = ap_const_logic_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    icmp_ln879_fu_597_p2 <= "1" when (cycle_V = ap_const_lv8_FF) else "0";
    iq_0_V_write_assign_fu_502_p3 <= (trunc_ln77_1_fu_428_p1 & trunc_ln77_fu_354_p1);
    iq_1_V_write_assign_fu_510_p3 <= (p_8_fu_432_p4 & p_1_fu_358_p4);
    iq_2_V_write_assign_fu_518_p3 <= (p_9_fu_442_p4 & p_2_fu_368_p4);
    iq_3_V_write_assign_fu_526_p3 <= (p_s_fu_452_p4 & p_3_fu_378_p4);
    iq_4_V_write_assign_fu_534_p3 <= (p_10_fu_462_p4 & p_4_fu_388_p4);
    iq_5_V_write_assign_fu_542_p3 <= (p_11_fu_472_p4 & p_5_fu_398_p4);
    iq_6_V_write_assign_fu_550_p3 <= (p_12_fu_482_p4 & p_6_fu_408_p4);
    iq_7_V_write_assign_fu_558_p3 <= (p_13_fu_492_p4 & p_7_fu_418_p4);

    istream_data_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, istream_data_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            istream_data_TDATA_blk_n <= istream_data_TVALID_int;
        else 
            istream_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    istream_data_TREADY_assign_proc : process(istream_data_TVALID, regslice_reverse_istream_data_U_ack_in)
    begin
        if (((istream_data_TVALID = ap_const_logic_1) and (regslice_reverse_istream_data_U_ack_in = ap_const_logic_1))) then 
            istream_data_TREADY <= ap_const_logic_1;
        else 
            istream_data_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    istream_data_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            istream_data_TREADY_int <= ap_const_logic_1;
        else 
            istream_data_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_0_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_0_TDATA_blk_n <= lane_0_TREADY_int;
        else 
            lane_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_0_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_0_TVALID <= regslice_forward_lane_0_data_V_U_vld_out;

    lane_0_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_0_TVALID_int <= ap_const_logic_1;
        else 
            lane_0_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_10_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_10_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_10_TDATA_blk_n <= lane_10_TREADY_int;
        else 
            lane_10_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_10_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_10_TVALID <= regslice_forward_lane_10_data_V_U_vld_out;

    lane_10_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_10_TVALID_int <= ap_const_logic_1;
        else 
            lane_10_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_11_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_11_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_11_TDATA_blk_n <= lane_11_TREADY_int;
        else 
            lane_11_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_11_TDATA_int <= 
        iq_5_V_write_assign_fu_542_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_11;
    lane_11_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_11_TVALID <= regslice_forward_lane_11_data_V_U_vld_out;

    lane_11_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_11_TVALID_int <= ap_const_logic_1;
        else 
            lane_11_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_12_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_12_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_12_TDATA_blk_n <= lane_12_TREADY_int;
        else 
            lane_12_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_12_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_12_TVALID <= regslice_forward_lane_12_data_V_U_vld_out;

    lane_12_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_12_TVALID_int <= ap_const_logic_1;
        else 
            lane_12_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_13_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_13_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_13_TDATA_blk_n <= lane_13_TREADY_int;
        else 
            lane_13_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_13_TDATA_int <= 
        iq_6_V_write_assign_fu_550_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_13;
    lane_13_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_13_TVALID <= regslice_forward_lane_13_data_V_U_vld_out;

    lane_13_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_13_TVALID_int <= ap_const_logic_1;
        else 
            lane_13_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_14_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_14_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_14_TDATA_blk_n <= lane_14_TREADY_int;
        else 
            lane_14_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_14_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_14_TVALID <= regslice_forward_lane_14_data_V_U_vld_out;

    lane_14_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_14_TVALID_int <= ap_const_logic_1;
        else 
            lane_14_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_15_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_15_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_15_TDATA_blk_n <= lane_15_TREADY_int;
        else 
            lane_15_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_15_TDATA_int <= 
        iq_7_V_write_assign_fu_558_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_15;
    lane_15_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_15_TVALID <= regslice_forward_lane_15_data_V_U_vld_out;

    lane_15_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_15_TVALID_int <= ap_const_logic_1;
        else 
            lane_15_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_1_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_1_TDATA_blk_n <= lane_1_TREADY_int;
        else 
            lane_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_1_TDATA_int <= 
        iq_0_V_write_assign_fu_502_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_1;
    lane_1_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_1_TVALID <= regslice_forward_lane_1_data_V_U_vld_out;

    lane_1_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_1_TVALID_int <= ap_const_logic_1;
        else 
            lane_1_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_2_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_2_TDATA_blk_n <= lane_2_TREADY_int;
        else 
            lane_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_2_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_2_TVALID <= regslice_forward_lane_2_data_V_U_vld_out;

    lane_2_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_2_TVALID_int <= ap_const_logic_1;
        else 
            lane_2_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_3_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_3_TDATA_blk_n <= lane_3_TREADY_int;
        else 
            lane_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_3_TDATA_int <= 
        iq_1_V_write_assign_fu_510_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_3;
    lane_3_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_3_TVALID <= regslice_forward_lane_3_data_V_U_vld_out;

    lane_3_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_3_TVALID_int <= ap_const_logic_1;
        else 
            lane_3_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_4_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_4_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_4_TDATA_blk_n <= lane_4_TREADY_int;
        else 
            lane_4_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_4_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_4_TVALID <= regslice_forward_lane_4_data_V_U_vld_out;

    lane_4_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_4_TVALID_int <= ap_const_logic_1;
        else 
            lane_4_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_5_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_5_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_5_TDATA_blk_n <= lane_5_TREADY_int;
        else 
            lane_5_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_5_TDATA_int <= 
        iq_2_V_write_assign_fu_518_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_5;
    lane_5_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_5_TVALID <= regslice_forward_lane_5_data_V_U_vld_out;

    lane_5_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_5_TVALID_int <= ap_const_logic_1;
        else 
            lane_5_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_6_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_6_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_6_TDATA_blk_n <= lane_6_TREADY_int;
        else 
            lane_6_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_6_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_6_TVALID <= regslice_forward_lane_6_data_V_U_vld_out;

    lane_6_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_6_TVALID_int <= ap_const_logic_1;
        else 
            lane_6_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_7_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_7_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_7_TDATA_blk_n <= lane_7_TREADY_int;
        else 
            lane_7_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_7_TDATA_int <= 
        iq_3_V_write_assign_fu_526_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_7;
    lane_7_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_7_TVALID <= regslice_forward_lane_7_data_V_U_vld_out;

    lane_7_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_7_TVALID_int <= ap_const_logic_1;
        else 
            lane_7_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_8_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_8_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_8_TDATA_blk_n <= lane_8_TREADY_int;
        else 
            lane_8_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_8_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_8_TVALID <= regslice_forward_lane_8_data_V_U_vld_out;

    lane_8_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_8_TVALID_int <= ap_const_logic_1;
        else 
            lane_8_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    lane_9_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, lane_9_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            lane_9_TDATA_blk_n <= lane_9_TREADY_int;
        else 
            lane_9_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lane_9_TDATA_int <= 
        iq_4_V_write_assign_fu_534_p3 when (trunc_ln791_fu_570_p1(0) = '1') else 
        last_V_9;
    lane_9_TLAST_int <= icmp_ln879_fu_597_p2(0);
    lane_9_TVALID <= regslice_forward_lane_9_data_V_U_vld_out;

    lane_9_TVALID_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lane_9_TVALID_int <= ap_const_logic_1;
        else 
            lane_9_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    p_10_fu_462_p4 <= qstream_data_TDATA_int(79 downto 64);
    p_11_fu_472_p4 <= qstream_data_TDATA_int(95 downto 80);
    p_12_fu_482_p4 <= qstream_data_TDATA_int(111 downto 96);
    p_13_fu_492_p4 <= qstream_data_TDATA_int(127 downto 112);
    p_1_fu_358_p4 <= istream_data_TDATA_int(31 downto 16);
    p_2_fu_368_p4 <= istream_data_TDATA_int(47 downto 32);
    p_3_fu_378_p4 <= istream_data_TDATA_int(63 downto 48);
    p_4_fu_388_p4 <= istream_data_TDATA_int(79 downto 64);
    p_5_fu_398_p4 <= istream_data_TDATA_int(95 downto 80);
    p_6_fu_408_p4 <= istream_data_TDATA_int(111 downto 96);
    p_7_fu_418_p4 <= istream_data_TDATA_int(127 downto 112);
    p_8_fu_432_p4 <= qstream_data_TDATA_int(31 downto 16);
    p_9_fu_442_p4 <= qstream_data_TDATA_int(47 downto 32);
    p_s_fu_452_p4 <= qstream_data_TDATA_int(63 downto 48);

    qstream_data_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, qstream_data_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            qstream_data_TDATA_blk_n <= qstream_data_TVALID_int;
        else 
            qstream_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    qstream_data_TREADY_assign_proc : process(qstream_data_TVALID, regslice_reverse_qstream_data_U_ack_in)
    begin
        if (((regslice_reverse_qstream_data_U_ack_in = ap_const_logic_1) and (qstream_data_TVALID = ap_const_logic_1))) then 
            qstream_data_TREADY <= ap_const_logic_1;
        else 
            qstream_data_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    qstream_data_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            qstream_data_TREADY_int <= ap_const_logic_1;
        else 
            qstream_data_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    select_ln43_10_fu_840_p3 <= 
        last_V_10 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_5_V_write_assign_fu_542_p3;
    select_ln43_12_fu_888_p3 <= 
        last_V_12 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_6_V_write_assign_fu_550_p3;
    select_ln43_14_fu_936_p3 <= 
        last_V_14 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_7_V_write_assign_fu_558_p3;
    select_ln43_2_fu_648_p3 <= 
        last_V_2 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_1_V_write_assign_fu_510_p3;
    select_ln43_4_fu_696_p3 <= 
        last_V_4 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_2_V_write_assign_fu_518_p3;
    select_ln43_6_fu_744_p3 <= 
        last_V_6 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_3_V_write_assign_fu_526_p3;
    select_ln43_8_fu_792_p3 <= 
        last_V_8 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_4_V_write_assign_fu_534_p3;
    select_ln43_fu_578_p3 <= 
        last_V_0 when (trunc_ln791_fu_570_p1(0) = '1') else 
        iq_0_V_write_assign_fu_502_p3;
    trunc_ln77_1_fu_428_p1 <= qstream_data_TDATA_int(16 - 1 downto 0);
    trunc_ln77_fu_354_p1 <= istream_data_TDATA_int(16 - 1 downto 0);
    trunc_ln791_fu_570_p1 <= cycle_V(1 - 1 downto 0);
end behav;
