// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_codeRepl5_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        istream_data_TDATA,
        istream_data_TVALID,
        istream_data_TREADY,
        qstream_data_TDATA,
        qstream_data_TVALID,
        qstream_data_TREADY,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] istream_data_TDATA;
input   istream_data_TVALID;
output   istream_data_TREADY;
input  [127:0] qstream_data_TDATA;
input   qstream_data_TVALID;
output   qstream_data_TREADY;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg istream_data_TREADY;
reg qstream_data_TREADY;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    istream_data_TDATA_blk_n;
reg    qstream_data_TDATA_blk_n;
reg    ap_block_state1;
wire   [15:0] trunc_ln69_fu_64_p1;
wire   [15:0] trunc_ln69_1_fu_138_p1;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [15:0] ap_return_5_preg;
reg   [15:0] ap_return_6_preg;
reg   [15:0] ap_return_7_preg;
reg   [15:0] ap_return_8_preg;
reg   [15:0] ap_return_9_preg;
reg   [15:0] ap_return_10_preg;
reg   [15:0] ap_return_11_preg;
reg   [15:0] ap_return_12_preg;
reg   [15:0] ap_return_13_preg;
reg   [15:0] ap_return_14_preg;
reg   [15:0] ap_return_15_preg;
reg   [0:0] ap_NS_fsm;
wire    regslice_reverse_istream_data_U_apdone_blk;
wire   [127:0] istream_data_TDATA_int;
wire    istream_data_TVALID_int;
reg    istream_data_TREADY_int;
wire    regslice_reverse_istream_data_U_ack_in;
wire    regslice_reverse_qstream_data_U_apdone_blk;
wire   [127:0] qstream_data_TDATA_int;
wire    qstream_data_TVALID_int;
reg    qstream_data_TREADY_int;
wire    regslice_reverse_qstream_data_U_ack_in;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
#0 ap_return_5_preg = 16'd0;
#0 ap_return_6_preg = 16'd0;
#0 ap_return_7_preg = 16'd0;
#0 ap_return_8_preg = 16'd0;
#0 ap_return_9_preg = 16'd0;
#0 ap_return_10_preg = 16'd0;
#0 ap_return_11_preg = 16'd0;
#0 ap_return_12_preg = 16'd0;
#0 ap_return_13_preg = 16'd0;
#0 ap_return_14_preg = 16'd0;
#0 ap_return_15_preg = 16'd0;
end

regslice_reverse #(
    .DataWidth( 128 ))
regslice_reverse_istream_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(istream_data_TDATA),
    .vld_in(istream_data_TVALID),
    .ack_in(regslice_reverse_istream_data_U_ack_in),
    .data_out(istream_data_TDATA_int),
    .vld_out(istream_data_TVALID_int),
    .ack_out(istream_data_TREADY_int),
    .apdone_blk(regslice_reverse_istream_data_U_apdone_blk)
);

regslice_reverse #(
    .DataWidth( 128 ))
regslice_reverse_qstream_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(qstream_data_TDATA),
    .vld_in(qstream_data_TVALID),
    .ack_in(regslice_reverse_qstream_data_U_ack_in),
    .data_out(qstream_data_TDATA_int),
    .vld_out(qstream_data_TVALID_int),
    .ack_out(qstream_data_TREADY_int),
    .apdone_blk(regslice_reverse_qstream_data_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= trunc_ln69_fu_64_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= {{qstream_data_TDATA_int[47:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= {{qstream_data_TDATA_int[63:48]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= {{qstream_data_TDATA_int[79:64]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= {{qstream_data_TDATA_int[95:80]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= {{qstream_data_TDATA_int[111:96]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= {{qstream_data_TDATA_int[127:112]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= {{istream_data_TDATA_int[31:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= {{istream_data_TDATA_int[47:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= {{istream_data_TDATA_int[63:48]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= {{istream_data_TDATA_int[79:64]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= {{istream_data_TDATA_int[95:80]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= {{istream_data_TDATA_int[111:96]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= {{istream_data_TDATA_int[127:112]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= trunc_ln69_1_fu_138_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 16'd0;
    end else begin
        if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= {{qstream_data_TDATA_int[31:16]}};
        end
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = trunc_ln69_fu_64_p1;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = {{istream_data_TDATA_int[31:16]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = {{qstream_data_TDATA_int[47:32]}};
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = {{qstream_data_TDATA_int[63:48]}};
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = {{qstream_data_TDATA_int[79:64]}};
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = {{qstream_data_TDATA_int[95:80]}};
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = {{qstream_data_TDATA_int[111:96]}};
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = {{qstream_data_TDATA_int[127:112]}};
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = {{istream_data_TDATA_int[47:32]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = {{istream_data_TDATA_int[63:48]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = {{istream_data_TDATA_int[79:64]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = {{istream_data_TDATA_int[95:80]}};
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = {{istream_data_TDATA_int[111:96]}};
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = {{istream_data_TDATA_int[127:112]}};
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = trunc_ln69_1_fu_138_p1;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = {{qstream_data_TDATA_int[31:16]}};
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        istream_data_TDATA_blk_n = istream_data_TVALID_int;
    end else begin
        istream_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_reverse_istream_data_U_ack_in == 1'b1) & (istream_data_TVALID == 1'b1))) begin
        istream_data_TREADY = 1'b1;
    end else begin
        istream_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        istream_data_TREADY_int = 1'b1;
    end else begin
        istream_data_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        qstream_data_TDATA_blk_n = qstream_data_TVALID_int;
    end else begin
        qstream_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_reverse_qstream_data_U_ack_in == 1'b1) & (qstream_data_TVALID == 1'b1))) begin
        qstream_data_TREADY = 1'b1;
    end else begin
        qstream_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        qstream_data_TREADY_int = 1'b1;
    end else begin
        qstream_data_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((qstream_data_TVALID_int == 1'b0) | (istream_data_TVALID_int == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign trunc_ln69_1_fu_138_p1 = qstream_data_TDATA_int[15:0];

assign trunc_ln69_fu_64_p1 = istream_data_TDATA_int[15:0];

endmodule //Block_codeRepl5_proc
